version: "3.9"

services:
  server:
    image: backendmovie:1.0.0
    container_name: ${SERVER_HOST}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/backend
      - server-v-node-modules:/backend/node_modules
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  database:
    image: database:1.0.0
    container_name: ${DATABASE_HOST}
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - moviedb-v:/data/db

volumes:
  server-v-node-modules:
  moviedb-v:
